config/routes.rb
Rewsley::Application.routes.draw do
  devise_for :users
  root "stories#index"
  resources :stories
  
  get 'search', to: 'stories#search'

end

app/models/story.rb
class Story < ActiveRecord::Base
	validates :title, :link, :category, :presence => true
	def self.search_for( query )
		Story.where("title LIKE :query OR category LIKE :query", :query => "%#{query}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  def index
    @stories = Story.search_for params[:q]
  end

  def show
    @story = Story.find params[:id]
  end

  def new
    @story = Story.new
  end

  def create
    safe_story_params = params.require(:story).permit(:title, :link, :category)
    @story = Story.new safe_story_params.merge(:upvotes => 1)

    if @story.save
      redirect_to @story
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsley</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1><a href="<%= root_path %>">Rewsley</a></h1>
	<%= notice %>
	<%= alert %>
	<%= bootstrap_flash %>

<%= yield %>

</body>
</html>

app/views/stories/_story.html.erb
<l1>
<h3><%= link_to story.title, story.link %></h3>
<p>
<b>Upvotes</b>: <%= story.upvotes %> ||
<b>Category</b>: <%= story.category %>
</p>
</li>

app/views/stories/index.html.erb
<h3><%= link_to "+ Add New Story", new_story_path %></h3>
<%= form_tag '/', method: :get do %>
<%= search_field_tag :q, params[:q] %>
<%= submit_tag "Search" %>
<% end %>
<br/>
<div id ="stories">
	<ul>
		<%= render @stories %>
	</ul>
</div>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
<h2>the following errors prevented your story from saving:</h2>
<ul>
	<% @story.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
<h1>Add a new story</h1>
<%= form_for @story do |f| %>
	<fieldset>
		<legend>Story</legend>
		<div>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div>
			<%= f.label :link %>
			<%= f.text_field :link %>
		</div>
		<div>
			<%= f.label :category %>
			<%= f.text_field :category %>
		</div>
	</fieldset>

	<%= f.submit "submit" %>
<% end %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<p><%= link_to @story.link, @story.link %></p>
<p><%= link_to "Back to home page", root_path %></p>